### ISSUE TITLE
Module doesn't appear to support kinesis-streams endpoint DNS construction

### ISSUE THREAD

**Issue by RomeLeader** [aws-samples/hub-and-spoke-with-shared-services-vpc-terraform#1]
I'm running into a similar problem in my own module, and found this while trying to solve it.

Most simple endpoints like EC2 and SSM only require a Route53 PHZ matching their service name.

Some, as identified in the module, like S3 or API Gateway, need a wildcard alias record.

However, there's a third case in the case of the kinesis-streams endpoint. To operate, it requires the following DNS:
```
kinesis.region.amazonaws.com

*.data-kinesis.region.amazonaws.com

*.control-kinesis.region.amazonaws.com
```

The output from dns_entry output only yields kinesis in this case, but the endpoint cannot be created without all 3.

**Comment by pablo19sc** [comment]
mmm interesting, thanks for pointing this out @RomeLeader. how do you solve this? I am thinking on maybe leaving the freedom to the module user to add as many variations of the dns_entry as they want.

Btw, I refactored the repo to remove some private modules, but I'm thinking on creating a specific module for VPC endpoints, so happy to get any feedback about this topic

**Comment by RomeLeader** [comment]
> mmm interesting, thanks for pointing this out @RomeLeader. how do you solve this? I am thinking on maybe leaving the freedom to the module user to add as many variations of the dns_entry as they want.
> 
> Btw, I refactored the repo to remove some private modules, but I'm thinking on creating a specific module for VPC endpoints, so happy to get any feedback about this topic

That's essentially what we did, yes. We borrowed your idea of packaging all the necessary info as an object per service, adding the phz_names as a list. For most simple endpoints it is a singleton list, but adds the flexibility necessary for Kinesis. For building large numbers of endpoints it's a little cumbersome, but it does work.

**Comment by pablo19sc** [comment]
I updated the repo with a private module that does this: it expects a list of aliases (taken from the locals.tf file) where the user can specific the different record names it wants in the private hosted zone (to point to the VPC endpoints).

Thank you very much for your feedback!
